
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun  9 2026 06:39:42 EDT (Jun  9 2026 10:39:42 UTC)

// Verification Directory fv/mult_4bit 

module mult_4bit(clk, rst_n, a, b, product);
  input clk, rst_n;
  input [3:0] a, b;
  output [7:0] product;
  wire clk, rst_n;
  wire [3:0] a, b;
  wire [7:0] product;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  DFFR_X1 \product_reg[6] (.RN (rst_n), .CK (clk), .D (n_70), .Q
       (product[6]), .QN (UNCONNECTED));
  OAI21_X1 g1075__2398(.A (n_69), .B1 (n_68), .B2 (n_67), .ZN (n_70));
  DFFR_X1 \product_reg[5] (.RN (rst_n), .CK (clk), .D (n_66), .Q
       (product[5]), .QN (UNCONNECTED0));
  DFFR_X1 \product_reg[7] (.RN (rst_n), .CK (clk), .D (n_65), .Q
       (product[7]), .QN (UNCONNECTED1));
  NAND2_X1 g1079__5107(.A1 (n_68), .A2 (n_67), .ZN (n_69));
  DFFR_X1 \product_reg[4] (.RN (rst_n), .CK (clk), .D (n_64), .Q
       (product[4]), .QN (UNCONNECTED2));
  XOR2_X2 g1076__6260(.A (n_62), .B (n_49), .Z (n_66));
  AOI21_X1 g1081__4319(.A (n_61), .B1 (n_63), .B2 (n_58), .ZN (n_68));
  OAI21_X1 g1082__8428(.A (n_11), .B1 (n_60), .B2 (n_25), .ZN (n_65));
  DFFR_X1 \product_reg[3] (.RN (rst_n), .CK (clk), .D (n_59), .Q
       (product[3]), .QN (UNCONNECTED3));
  XOR2_X2 g1083__5526(.A (n_63), .B (n_56), .Z (n_64));
  AOI21_X1 g1084__6783(.A (n_57), .B1 (n_63), .B2 (n_54), .ZN (n_62));
  INV_X2 g1086(.A (n_60), .ZN (n_61));
  XOR2_X2 g1085__3680(.A (n_55), .B (n_51), .Z (n_59));
  OAI21_X1 g1087__1617(.A (n_58), .B1 (n_57), .B2 (n_44), .ZN (n_60));
  AOI21_X1 g1089__2802(.A (n_57), .B1 (n_53), .B2 (n_52), .ZN (n_56));
  OAI21_X1 g1088__1705(.A (n_50), .B1 (n_48), .B2 (n_55), .ZN (n_63));
  NAND2_X1 g1095__5122(.A1 (n_53), .A2 (n_52), .ZN (n_54));
  NOR2_X2 g1093__8246(.A1 (n_53), .A2 (n_52), .ZN (n_57));
  DFFR_X1 \product_reg[2] (.RN (rst_n), .CK (clk), .D (n_45), .Q
       (product[2]), .QN (UNCONNECTED4));
  OAI21_X1 g1090__7098(.A (n_50), .B1 (n_47), .B2 (n_46), .ZN (n_51));
  NAND2_X1 g1092__6131(.A1 (n_58), .A2 (n_43), .ZN (n_49));
  NAND2_X1 g1094__1881(.A1 (n_47), .A2 (n_46), .ZN (n_50));
  INV_X2 g1097(.A (n_42), .ZN (n_45));
  INV_X2 g1098(.A (n_43), .ZN (n_44));
  AOI21_X1 g1102__5115(.A (n_39), .B1 (n_34), .B2 (n_33), .ZN (n_52));
  OAI21_X1 g1099__7482(.A (n_55), .B1 (n_38), .B2 (n_37), .ZN (n_42));
  NAND2_X1 g1100__4733(.A1 (n_41), .A2 (n_40), .ZN (n_43));
  OR2_X2 g1101__6161(.A1 (n_41), .A2 (n_40), .ZN (n_58));
  XOR2_X2 g1103__9315(.A (n_32), .B (n_28), .Z (n_53));
  INV_X2 g1106(.A (n_36), .ZN (n_39));
  XOR2_X2 g1104__9945(.A (n_35), .B (n_20), .Z (n_47));
  NAND2_X1 g1105__2883(.A1 (n_38), .A2 (n_37), .ZN (n_55));
  OAI21_X1 g1107__2346(.A (n_35), .B1 (n_34), .B2 (n_33), .ZN (n_36));
  OAI21_X1 g1108__1666(.A (n_29), .B1 (n_31), .B2 (n_30), .ZN (n_41));
  AOI22_X1 g1111__7410(.A1 (n_31), .A2 (n_26), .B1 (n_27), .B2 (n_30),
       .ZN (n_32));
  OAI21_X1 g1110__6417(.A (n_19), .B1 (n_18), .B2 (n_24), .ZN (n_38));
  OAI21_X1 g1109__5477(.A (n_28), .B1 (n_27), .B2 (n_26), .ZN (n_29));
  OAI21_X1 g1113__2398(.A (n_23), .B1 (n_22), .B2 (n_21), .ZN (n_35));
  XOR2_X2 g1112__5107(.A (n_12), .B (n_16), .Z (n_40));
  NOR2_X2 g1118__6260(.A1 (n_25), .A2 (n_10), .ZN (n_67));
  NOR2_X2 g1116__4319(.A1 (n_17), .A2 (n_24), .ZN (n_46));
  DFFR_X1 \product_reg[1] (.RN (rst_n), .CK (clk), .D (n_15), .Q
       (product[1]), .QN (UNCONNECTED5));
  NAND2_X1 g1117__8428(.A1 (n_22), .A2 (n_21), .ZN (n_23));
  XOR2_X2 g1119__5526(.A (n_34), .B (n_33), .Z (n_20));
  NAND2_X1 g1115__6783(.A1 (n_18), .A2 (n_24), .ZN (n_19));
  OAI22_X1 g1120__3680(.A1 (n_9), .A2 (n_21), .B1 (n_13), .B2 (n_14),
       .ZN (n_28));
  INV_X4 g1121(.A (n_18), .ZN (n_17));
  AOI21_X1 g1122__1617(.A (n_16), .B1 (a[3]), .B2 (b[3]), .ZN (n_25));
  INV_X2 g1125(.A (n_27), .ZN (n_31));
  XOR2_X2 g1126__2802(.A (n_8), .B (n_7), .Z (n_15));
  XOR2_X2 g1123__1705(.A (n_14), .B (n_13), .Z (n_22));
  XOR2_X2 g1124__5122(.A (n_2), .B (n_1), .Z (n_18));
  XOR2_X2 g1127__8246(.A (n_6), .B (n_5), .Z (n_12));
  INV_X4 g1129(.A (n_10), .ZN (n_11));
  XOR2_X2 g1128__7098(.A (n_4), .B (n_3), .Z (n_27));
  DFFR_X1 \product_reg[0] (.RN (rst_n), .CK (clk), .D (n_0), .Q
       (product[0]), .QN (UNCONNECTED6));
  AND2_X2 g1131__6131(.A1 (n_14), .A2 (n_13), .ZN (n_9));
  NOR2_X2 g1133__1881(.A1 (n_8), .A2 (n_7), .ZN (n_37));
  NOR2_X2 g1132__5115(.A1 (n_6), .A2 (n_5), .ZN (n_10));
  NOR2_X2 g1134__7482(.A1 (n_4), .A2 (n_3), .ZN (n_16));
  NOR2_X2 g1135__4733(.A1 (n_2), .A2 (n_1), .ZN (n_34));
  INV_X2 g1143(.A (n_30), .ZN (n_26));
  NAND2_X1 g1138__6161(.A1 (a[2]), .A2 (b[3]), .ZN (n_6));
  NAND2_X1 g1137__9315(.A1 (a[3]), .A2 (b[2]), .ZN (n_5));
  NAND2_X1 g1146__9945(.A1 (a[1]), .A2 (b[0]), .ZN (n_7));
  NAND2_X1 g1149__2883(.A1 (a[1]), .A2 (b[2]), .ZN (n_13));
  NAND2_X1 g1150__2346(.A1 (a[3]), .A2 (b[1]), .ZN (n_30));
  NAND2_X1 g1141__1666(.A1 (a[1]), .A2 (b[1]), .ZN (n_24));
  NAND2_X1 g1151__7410(.A1 (a[0]), .A2 (b[3]), .ZN (n_14));
  AND2_X2 g1136__6417(.A1 (a[0]), .A2 (b[0]), .ZN (n_0));
  NAND2_X1 g1144__5477(.A1 (a[1]), .A2 (b[3]), .ZN (n_4));
  NAND2_X1 g1139__2398(.A1 (a[2]), .A2 (b[0]), .ZN (n_1));
  NAND2_X1 g1147__5107(.A1 (a[0]), .A2 (b[2]), .ZN (n_2));
  NAND2_X1 g1145__6260(.A1 (a[2]), .A2 (b[2]), .ZN (n_3));
  NAND2_X1 g1148__4319(.A1 (a[0]), .A2 (b[1]), .ZN (n_8));
  AND2_X2 g1142__8428(.A1 (a[2]), .A2 (b[1]), .ZN (n_33));
  NAND2_X1 g1140__5526(.A1 (a[3]), .A2 (b[0]), .ZN (n_21));
  INV_X4 g1160(.A (n_47), .ZN (n_48));
endmodule

